name: CI

##############################################################
# Triggers when push changes occur in specified branch paths #
##############################################################
on:
  push:
    branches-ignore:
      - main
      - '!v[0-9]+.[0-9]+.[0-9]+*'
    paths:
      - 'src/**'
      - '.github/workflows/continuos-integration.yml'

###################
# Set Global Envs #
###################
env:
  NODE_VERSION: '14'

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  continuos-integration:
    name: Continuos Integration
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      #################
      # Setup Node JS #
      #################
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      ################
      # Install Deps #
      ################
      - name: Install Deps
        working-directory: .
        shell: bash
        run: npm install

      ################
      # Check Format #
      ################
      - name: Check Format
        working-directory: .
        shell: bash
        run: npm run format:check

      #################
      # Build Package #
      #################
      - name: Build Package
        working-directory: .
        shell: bash
        run: npm run build
