name: npm

###################################################
# Start the job on semantic versioned branch push #
###################################################
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

###################
# Set Global Envs #
###################
env:
  node_version: '12'

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  publish-github-package:
    name: Publish GitHub Package
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      ###############
      # Get Version #
      ###############
      - name: Get Version
        shell: bash
        run: |
          pattern="refs/heads/"
          ver="${github_ref/$pattern/}"
          echo $ver
          echo "new_version=$ver" >> $GITHUB_ENV
        env:
          github_ref: ${{ github.ref }}

      #################
      # Setup Node JS #
      #################
      - name: Setup Node JS
        # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@qbcart'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.QBC_GITHUB_PACKAGES }}

      ################
      # Install Deps #
      ################
      - name: Install Deps
        working-directory: .
        shell: bash
        run: npm install

      #################
      # Build Package #
      #################
      - name: Build Package
        working-directory: .
        shell: bash
        run: npm run build

      ######################
      # Copy Package Files #
      ######################
      - name: Copy Package Files
        working-directory: .
        shell: bash
        run: |
          cp package.json dist
          cp README.md dist

      ###################
      # Publish Package #
      ###################
      - name: Publish Package
        working-directory: dist
        shell: bash
        run: |
          npm version $ver
          echo 'VER:' $ver
          npm publish
        env:
          ver: ${{ env.new_version }}
